// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYTh9EH6Q7C3RGaKcM2Jkc63Q4Mbv3wM',
    appId: '1:758093226180:web:0b1a9a2ba40e2f3c242991',
    messagingSenderId: '758093226180',
    projectId: 'prueba-2-35f87',
    authDomain: 'prueba-2-35f87.firebaseapp.com',
    storageBucket: 'prueba-2-35f87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVma3ePwK1PmL5K3p3wMEKrb-Dp5GKnc',
    appId: '1:758093226180:android:0499358a50f0d2c3242991',
    messagingSenderId: '758093226180',
    projectId: 'prueba-2-35f87',
    storageBucket: 'prueba-2-35f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cEa-MIXacyjrXYwvD2MmTWn-1VgyqEo',
    appId: '1:758093226180:ios:102191a1b38c8a95242991',
    messagingSenderId: '758093226180',
    projectId: 'prueba-2-35f87',
    storageBucket: 'prueba-2-35f87.appspot.com',
    iosBundleId: 'com.example.segurapp',
  );
}
