// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYTh9EH6Q7C3RGaKcM2Jkc63Q4Mbv3wM',
    appId: '1:758093226180:web:0b1a9a2ba40e2f3c242991',
    messagingSenderId: '758093226180',
    projectId: 'prueba-2-35f87',
    authDomain: 'prueba-2-35f87.firebaseapp.com',
    storageBucket: 'prueba-flutter-cc06e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnM6ElvWSNR2hFe-l3zuFKgZ3MVVhqLU',
    appId: '1:758093226180:android:0499358a50f0d2c3242991',
    messagingSenderId: '758093226180',
    projectId: 'prueba-2-35f87',
    storageBucket: 'prueba-flutter-cc06e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPQDd8qHiPUzF5bV4a1RjRgAeDnbOdUI',
    appId: '1:680783185386:ios:9f664b7800beceacc49e93',
    messagingSenderId: '758093226180',
    projectId: 'prueba-flutter-cc06e',
    storageBucket: 'prueba-flutter-cc06e.appspot.com',
    iosBundleId: 'com.example.segurapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPQDd8qHiPUzF5bV4a1RjRgAeDnbOdUI',
    appId: '1:680783185386:ios:9f664b7800beceacc49e93',
    messagingSenderId: '758093226180',
    projectId: 'prueba-flutter-cc06e',
    storageBucket: 'prueba-flutter-cc06e.appspot.com',
    iosBundleId: 'com.example.segurapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjlJYXKMpDUUxdlIxdEE0DoRt4hSD5BwM',
    appId: '1:680783185386:web:ba6206eb2653c6b2c49e93',
    messagingSenderId: '758093226180',
    projectId: 'prueba-flutter-cc06e',
    authDomain: 'prueba-flutter-cc06e.firebaseapp.com',
    storageBucket: 'prueba-flutter-cc06e.appspot.com',
  );

}